@startuml

!function $Requirement($sterotype, $block, $id, $title, $descr="") 
rectangle "[$block] $title\n\n $descr" <<$sterotype>> as $id 
!endfunction

!function RR($id, $title, $descr="") 
$Requirement("RR", "Sys", $id, $title, $descr)
!endfunction

!function IR($id, $title, $descr="") 
$Requirement("IR", "Sys", $id, $title, $descr)
!endfunction

!function SF($id, $title, $descr="") 
$Requirement("SF", "Sys", $id, $title, $descr)
!endfunction

!function SR($id, $title, $descr="") 
$Requirement("SR", "Sys", $id, $title, $descr)
!endfunction

!function AR($id, $bb, $title, $descr="") 
$Requirement("AR", $bb, $id, $title, $descr)
!endfunction


' Relationships

!define Rel_(e_alias1, e_alias2, e_label, e_direction="") e_alias1 e_direction e_alias2 : "===e_label"
!define Rel_(e_alias1, e_alias2, e_label, e_techn, e_direction="") e_alias1 e_direction e_alias2 : "===e_label\n//<size:TECHN_FONT_SIZE>[e_techn]</size>//"

!define Rel(e_from,e_to, e_label) Rel_(e_from,e_to, e_label, "-->")
!define Rel(e_from,e_to, e_label, e_techn) Rel_(e_from,e_to, e_label, e_techn, "-->")

!function $rel($from, $to, $label, $direction="")
$from $direction $to : "$label"
!endfunction

!function $dependency($from, $to)
$rel($from, $to, "dependency", "..>")
!endfunction

!define Dep(from, to) $dependency(from, to)

!function Trace($from, $to) 
$rel($from, $to, "tracedTo", "..>")
!endfunction

!function TraceLine($req1, $req2, $req3) 
Trace($req1, $req2)
Trace($req2, $req3)
!endfunction

!function TraceLine($req1, $req2, $req3, $req4) 
Trace($req1, $req2)
Trace($req2, $req3)
Trace($req3, $req4)
!endfunction

!function TraceLine($req1, $req2, $req3, $req4, $req5) 
Trace($req1, $req2)
Trace($req2, $req3)
Trace($req3, $req4)
Trace($req4, $req5)
!endfunction

@enduml
